# Generated by Django 3.2 on 2021-04-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('chair', models.CharField(max_length=50)),
                ('organisateur', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('lieu', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
