# Generated by Django 3.2 on 2021-05-02 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accueil', '0002_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='conférence',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Accueil.conference'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='motsClé',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
