# Generated by Django 3.2 on 2021-05-04 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accueil', '0003_auto_20210502_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='conférence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Articles', to='Accueil.conference'),
        ),
        migrations.AlterField(
            model_name='article',
            name='motsClé',
            field=models.CharField(max_length=300),
        ),
    ]
