# Generated by Django 3.2 on 2021-05-06 16:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Accueil', '0004_auto_20210504_1420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='conference',
            options={'verbose_name': 'Conférence', 'verbose_name_plural': 'Conférences'},
        ),
        migrations.AddField(
            model_name='article',
            name='date_publication',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(default="c'est un text qui parle sur java "),
            preserve_default=False,
        ),
    ]
