# Generated by Django 3.2 on 2021-05-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accueil', '0005_auto_20210506_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MotCle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mot', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='auteur',
        ),
        migrations.RemoveField(
            model_name='article',
            name='motsClé',
        ),
        migrations.AddField(
            model_name='article',
            name='auteurs',
            field=models.ManyToManyField(to='Accueil.Auteur'),
        ),
        migrations.AddField(
            model_name='article',
            name='motsClé',
            field=models.ManyToManyField(to='Accueil.MotCle'),
        ),
    ]
