# Generated by Django 3.2 on 2021-05-31 13:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Accueil', '0006_auto_20210515_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='fichier',
            field=models.FileField(default=django.utils.timezone.now, upload_to='media'),
            preserve_default=False,
        ),
    ]
