# Generated by Django 3.2 on 2021-06-14 10:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Accueil', '0008_auto_20210531_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='auteur',
            name='prenom',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
