# Generated by Django 3.2 on 2021-06-18 19:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Accueil', '0009_auteur_prenom'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='langue',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
