# Generated by Django 3.2 on 2021-06-22 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accueil', '0010_article_langue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor_Infos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('page_visited', models.TextField()),
                ('event_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
