# Generated by Django 3.2 on 2021-06-23 11:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Accueil', '0011_visitor_infos'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='audience',
            field=models.CharField(choices=[('Nationale', 'Nationale'), ('Internationale', 'Internationale')], default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conference',
            name='nom',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='motcle',
            name='mot',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
