# Generated by Django 3.2 on 2021-06-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accueil', '0012_auto_20210623_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='label',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
