# Generated by Django 3.2 on 2021-07-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accueil', '0013_conference_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='description',
            new_name='résumé',
        ),
        migrations.AlterField(
            model_name='conference',
            name='audience',
            field=models.CharField(choices=[('Internationale', 'Internationale'), ('Nationale', 'Nationale')], max_length=15),
        ),
    ]
